# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c5d8878214ed182396626a9f2e155a5b498b294e83deac155cfb99633c35811cffe8289d4bdceffc01b16bdc45bcb85945e6f83a73fcc2b2130cab4e378dccab

test:
  secret_key_base: 74505947232875d91cd51170f055c6a6579ef3d29d1dcb2813a37b1caf50de755e7dbef5a32c43dd35ef57610140a3f5cd85b22cd991208f0cb4e39a43d17df1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
